FROM conanio/gcc9:1.62.0 
LABEL Description="Build environment"

ENV HOME /src

SHELL ["/bin/bash", "-c"]

RUN pip install --upgrade pip
RUN pip install conan==1.60.1 graphviz Sphinx recommonmark sphinx_markdown_tables sphinx-rtd-theme sphinx_book_theme exhale

CMD ["/bin/bash","cd /src"] 
